[package]
name = "raytracer_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
glam = "0.29.2"
getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen = "0.2.99"
